apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-mysql
  template:
    metadata:
      labels:
        app: myapp-mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "myappdb"
        - name: MYSQL_USER
          value: "myuser"
        - name: MYSQL_PASSWORD
          value: "mypassword"
        volumeMounts:
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: init-sql
        configMap:
          name: init-sql-config
      - name: mysql-data
        emptyDir: {}  # في بيئة حقيقية قد تستخدم PersistentVolumeClaim
