apiVersion: v1
kind: Service
metadata:
  name: php-service
spec:
  selector:
    app: myapp-php
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort  # للسماح بالوصول من خارج الـ Cluster (في Minikube أو غيره)
